.\" Specify the font family for export with other postprocessors.
.fam N
.NHR

.URL https://github.com/mibi88/ld58 \
"Garbage collector's minion (Ludum Dare 58 jam)"
A small game where you are an allocator and the garbage collector asks you to
perform some tasks.
.URL https://mibi88.itch.io/garbage-collectors-minion "itch.io"\&).

bootris A small 510 bytes (+2 byte magic number to make it bootable) clone of 
the famous video game with falling tetrominos written in 16bit real mode x86 
assembly (unfinished, having some trouble to fit more code in it).

.URL https://github.com/mibi88/mushroom_champ/ mushroom_champ
A small game for the NES where one farms giant mushrooms (unfinished).

.URL https://github.com/mibi88/ld57 "GOLD HUNGER (Ludum Dare 57 jam)"
A small game made with
.URL https://github.com/mibi88/MibiEngine2/ MibiEngine2
where you need to eat some minerals as fast as possible or you starve (play it 
on
.URL https://mibi88.itch.io/gold-hunger "itch.io"\&).

Tangris A game for the NES similar to the well known game with falling 
tetrominos, but with tangram pieces instead :D, written in assembly (not 
finished yet).

Lifeless A small puzzling platformer for the NES (not finished yet).

.URL https://github.com/mibi88/ld56 "Antwars (Ludum Dare 56 compo)"
A small strategy game. (play it on
.URL https://mibi88.itch.io/antwars "itch.io"\&).

.URL https://github.com/mibi88/simple_raycaster "Simple raycaster"
A very fast raycaster.

.URL https://github.com/mibi88/ld55 "The seven crystals (Ludum Dare 55 jam)"
A dungeon exploration game where you fight mobs in procedurally generated 
dungeons. (play it on
.URL https://mibi88.itch.io/the-seven-crystals "itch.io"\&)

Solitude A small platformer for the NES (not finished yet).

.URL https://github.com/mibi88/dino_nes "Dino NES"
A dino game for the NES. (play it on
.URL https://mibi88.itch.io/dino-nes "itch.io"\&)

.URL https://github.com/mibi88/MibiCraft MibiCraft
A small sandbox building game (not finished at all).

.URL https://github.com/mibi88/MossyDungeon MossyDungeon
A speedrunning platformer where the floor breaks after some time. (play it on 
.URL https://mibi88.itch.io/mossydungeons "itch.io"\&)

.URL https://github.com/mibi88/BREAKMOLE BREAKMOLE
Whac-A-Mole + BREAKOUT for a twice as fun experience! (play it on
.URL https://mibi88.itch.io/breakmole "itch.io"\&)

.URL https://github.com/mibi88/MibiFlightSimulator MibiFlightSimulator
A small unrealistic flight simulator.

.URL https://github.com/mibi88/CalcRace CalcRace
A small game to get better in mental calculation!

.URL https://github.com/mibi88/neslib_ship_battle "Neslib ship battle"
One of my first video games! It's the first real program I wrote in C (the code 
is awful)
