.\" Specify the font family for export with other postprocessors.
.fam N
.NHR

.URL https://github.com/mibi88/3d_pyxel "3D Pyxel demo"
Some very basic 3D. This small demo was made in ca. 6h without searching 
anything on the internet (but I fixed some bugs since, by searching the correct 
formulas online).

.URL https://github.com/mibi88/limg limg
My image format that uses RGB565 colors (but it has no compression).
